# -*- coding: utf-8 -*-
"""PythonTradingScript.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lEZeDux4H8PqqLMCW5MaG3M21-dSPG7n
"""

import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

from google.colab import files
uploaded = files.upload()

AAPL = pd.read_csv('aapl.csv')

AAPL

plt.figure(figsize=(12.5, 4.5))
plt.plot(AAPL['Close'], label = 'AAPL')
plt.title('Apple Adj. Close Price History')
plt.xlabel('Oct. 02, 2006 - Dec. 30, 2011')
plt.ylabel('Adj. Close Price USD ($)')
plt.legend(loc='upper left')
plt.show()

SMA30 = pd.DataFrame()
SMA30['Close'] = AAPL['Close'].rolling(window=30).mean()
SMA30

SMA100 = pd.DataFrame()
SMA100 ['Close'] = AAPL['Close'].rolling(window=100).mean()
SMA100

plt.figure(figsize=(12.5, 4.5))
plt.plot(AAPL['Close'], label = 'AAPL')
plt.plot(SMA30['Close'], label='SMA30') 
plt.plot(SMA100['Close'], label='SMA100') 
plt.title('Apple Adj. Close Price History')
plt.xlabel('Oct. 02, 2006 - Dec. 30, 2011')
plt.ylabel('Adj. Close Price USD ($)')
plt.legend(loc='upper left')
plt.show()

data = pd.DataFrame()
data['AAPL'] = AAPL['Close']
data['SMA30']= SMA30['Close']
data['SMA100']= SMA100['Close']
data

def buy_sell(data):
  sigPriceBuy = []
  sigPriceSell = []
  flag = -1

  for i in range(len(data)):
    if data['SMA30'][i] > data['SMA100'][i]:
      if flag != 1:
        sigPriceBuy.append(data['AAPL'][i])
        sigPriceSell.append(np.nan)
        flag = 1
      else:
        sigPriceBuy.append(np.nan)
        sigPriceSell.append(np.nan)
    elif data['SMA30'][i] < data['SMA100'][i]:
      if flag !=0:
          sigPriceBuy.append(np.nan)
          sigPriceSell.append(data['AAPL'][i])
          flag = 0
      else:
           sigPriceBuy.append(np.nan)
           sigPriceSell.append(np.nan)
    else:
            sigPriceBuy.append(np.nan)
            sigPriceSell.append(np.nan)

  return (sigPriceBuy, sigPriceSell)

x = buy_sell(data)
data['Buy_Signal_Price'] = x[0]
data['Sell_Signal_Price'] = x[1]

data

plt.figure(figsize=(12.6, 4.6))
plt.plot(data['AAPL'], label='AAPL', alpha = 0.35)
plt.plot(data['SMA30'], label = 'SMA30', alpha = 0.35)
plt.plot(data['SMA100'], label = 'SMA100', alpha = 0.35)
plt.scatter(data.index, data['Buy_Signal_Price'], label = 'Buy', marker = '^', color='green')
plt.scatter(data.index, data['Sell_Signal_Price'], label = 'Buy', marker = 'v', color='red')
plt.title('Apple Close Price History Buy and Sell Signals')
plt.xlabel('Oct. 02, 2006 - Dec. 30, 2011')
plt.ylabel('Adj Close Price USD($)')
plt.legend(loc='upper left')
plt.show()